# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'MarvelApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp
  pod "Dip"
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'CryptoSwift'
  pod 'SwiftyJSON'
  pod 'SDWebImage'

  target 'MarvelAppTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'MarvelAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
