# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'MarvelApp' do
  use_frameworks!
  # Pods for MarvelApp
  pod 'Dip'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'CryptoSwift'
  pod 'SwiftyJSON'
  pod 'SDWebImage'

  target 'MarvelAppUnitTests' do
    use_frameworks!
    inherit! :search_paths
    pod 'InstantMock'
  end
end
